### ISSUE TITLE
http://dashit.czbiohub.org/ instructions

### ISSUE THREAD

**Issue by emilydc** [czbiohub/dashit#20]
Just a heads up, in case you aren't already aware, that the instructions at  http://dashit.czbiohub.org/ don't seem to work. When I follow them it doesn't seem to install score_guides at all, and it has the `ash` problem as well. I'll stop giving people the address http://dashit.czbiohub.org/ for the moment until it is working.

**Comment by EmperorDali** [comment]
This is all fixed now, thanks for the report!
